In [106]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from xgboost import XGBClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

In [2]:
df = pd.read_csv("Heart Attack Data Set.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

- age = umur pasien
- sex = gender pasien
- cp = level chest pain
- trestbps = nilai tekanan darah
- chol = nilai kolestrol
- fbs = nilai gula darah
- restecg = hasil ECG
- thalach = max heart rate
- exang = exercise angina
- oldpeak = ST depression
- slope = ST slope
- ca = major vessels
- thal = level thalassemia
- target = heart attack risk

In [3]:
df.shape

(303, 14)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [5]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [6]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(1)

In [8]:
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [9]:
num_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
bin_cols = ['sex', 'fbs', 'exang']
ordinal_cols = ['cp', 'restecg', 'slope', 'ca', 'thal']

In [10]:
x = df.drop("target", axis = 1)
y = df["target"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [50]:
num_transformers = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
ordinal_transformers = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent'))
])

preprocessor = ColumnTransformer([
    ('num', num_transformers, num_cols),
    ('ord', ordinal_transformers, ordinal_cols),
    ('bin', 'passthrough', bin_cols)
])

lr = LogisticRegression(
    max_iter = 1000,
    C = 1.0,
    class_weight = 'balanced'
)

rf = RandomForestClassifier(
    n_estimators = 300,
    max_depth = 6,
    min_samples_split = 6
)

xgb = XGBClassifier(
    tree_method = 'hist',
    n_estimators = 300,
    max_depth = 7,
    learning_rate = 0.05
)

In [51]:

log_model = Pipeline([
    ('preprocessing', preprocessor),
    ('lr', lr)
])

rf_model = Pipeline([
    ('preprocessing', preprocessor),
    ('rf', rf)
])

xgb_model = Pipeline([
    ('preprocessing', preprocessor),
    ('xgb', xgb)
])

In [52]:
log_model.fit(x_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'trestbps', 'chol',
                                                   'thalach', 'oldpeak']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent'))]),
                                                  ['cp', 'restecg', 'slope',
                                                   'ca', 'thal']),
                                                 ('bin', 'passthrough',
                                                  ['sex', 'fbs', 'exang'])])),
                ('lr',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [53]:
rf_model.fit(x_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'trestbps', 'chol',
                                                   'thalach', 'oldpeak']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent'))]),
                                                  ['cp', 'restecg', 'slope',
                                                   'ca', 'thal']),
                                                 ('bin', 'passthrough',
                                                  ['sex', 'fbs', 'exang'])])),
                ('rf',
                 RandomForestClassifier(max_depth=6, min_samples_split=6,
                                        n_estimators=300))])

In [54]:
xgb_model.fit(x_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'trestbps', 'chol',
                                                   'thalach', 'oldpeak']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent'))]),
                                                  ['cp', 'restecg', 'slope',
                                                   'ca', 'thal']),
                                                 ('bin', 'passthrough',
                                                  ['se...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=7, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [55]:
log_pred = log_model.predict(x_test)
rf_pred = rf_model.predict(x_test)
xgb_pred = xgb_model.predict(x_test)

In [56]:
log_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [57]:
rf_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [58]:
xgb_pred

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [71]:
print(f'roc_auc_score (LogisticRegression) : {roc_auc_score(y_test, log_pred)}')
print(f'roc_auc_score (RandomForestClassifier) : {roc_auc_score(y_test, rf_pred)}')
print(f'roc_auc_score (XGBClassifier) : {roc_auc_score(y_test, xgb_pred)}')

roc_auc_score (LogisticRegression) : 0.8529094827586207
roc_auc_score (RandomForestClassifier) : 0.8669181034482758
roc_auc_score (XGBClassifier) : 0.8372844827586207


In [59]:
result = pd.DataFrame({
    'actual' : y_test,
    'log_pred' : log_pred,
    'rf_pred' : rf_pred,
    'xgb_pred' : xgb_pred
})

In [60]:
result.head(20)

actual  log_pred  rf_pred  xgb_pred
179       0         0        0         0
228       0         1        1         0
111       1         1        1         0
246       0         0        0         0
60        1         1        1         1
9         1         1        1         1
119       1         1        1         1
223       0         0        0         0
268       0         0        0         0
33        1         0        1         0
5         1         1        1         1
101       1         0        0         0
45        1         1        1         1
175       0         0        0         0
118       1         1        1         1
46        1         1        1         1
125       1         1        1         1
192       0         0        0         0
285       0         0        0         0
279       0         0        0         0

In [85]:
log_param = {
    'lr__max_iter' : [1000, 1200, 1500],
    'lr__C' : [0.1, 1.0, 10],
    'lr__class_weight' : [None, 'balanced']
}

rf_param = {
    'rf__n_estimators' : [200, 300, 500],
    'rf__max_depth' : [5, 6, 8],
    'rf__min_samples_split' : [5, 6, 7]
}

xgb_param = {
    'xgb__n_estimator' : [200, 300, 500],
    'xgb__max_depth' : [3, 5, 7, 9],
    'xgb__learning_rate' : [0.01, 0.05, 0.1]
}

In [90]:
log_grid = GridSearchCV(
    estimator = log_model,
    param_grid = log_param,
    cv = 5,
    scoring = "roc_auc",
    n_jobs = -1
)

rf_grid = GridSearchCV(
    estimator = rf_model,
    param_grid = rf_param,
    cv = 5,
    scoring = 'roc_auc',
    n_jobs = -1
)

xgb_grid = GridSearchCV(
    estimator = xgb_model,
    param_grid = xgb_param,
    cv = 5,
    scoring = 'roc_auc',
    n_jobs = -1
)

In [94]:
log_grid.fit(x_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['age',
                                                                          'trestbps',
                                                                          'chol',
                                                                          'thalach',
                                                                          'oldpeak']),
                                                                        ('ord',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='most_frequent'))]),
                                                                         ['cp',
                                                                          'restecg',
                                                                          'slope',
                                                                          'ca',
                                                                          'thal']),
                                                                        ('bin',
                                                                         'passthrough',
                                                                         ['sex',
                                                                          'fbs',
                                                                          'exang'])])),
                                       ('lr',
                                        LogisticRegression(class_weight='balanced',
                                                           max_iter=1000))]),
             n_jobs=-1,
             param_grid={'lr__C': [0.1, 1.0, 10],
                         'lr__class_weight': [None, 'balanced'],
                         'lr__max_iter': [1000, 1200, 1500]},
             scoring='roc_auc')

In [95]:
rf_grid.fit(x_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['age',
                                                                          'trestbps',
                                                                          'chol',
                                                                          'thalach',
                                                                          'oldpeak']),
                                                                        ('ord',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='most_frequent'))]),
                                                                         ['cp',
                                                                          'restecg',
                                                                          'slope',
                                                                          'ca',
                                                                          'thal']),
                                                                        ('bin',
                                                                         'passthrough',
                                                                         ['sex',
                                                                          'fbs',
                                                                          'exang'])])),
                                       ('rf',
                                        RandomForestClassifier(max_depth=6,
                                                               min_samples_split=6,
                                                               n_estimators=300))]),
             n_jobs=-1,
             param_grid={'rf__max_depth': [5, 6, 8],
                         'rf__min_samples_split': [5, 6, 7],
                         'rf__n_estimators': [200, 300, 500]},
             scoring='roc_auc')

In [96]:
xgb_grid.fit(x_train, y_train)

c:\Users\willi\anaconda3\envs\model_deployment\Lib\site-packages\xgboost\training.py:200: UserWarning: [13:52:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782: 
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['age',
                                                                          'trestbps',
                                                                          'chol',
                                                                          'thalach',
                                                                          'oldpeak']),
                                                                        ('ord',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='most_frequent'))]),
                                                                         ['cp',
                                                                          'restecg',
                                                                          'slope',
                                                                          'ca',
                                                                          'thal'...
                                                      max_cat_threshold=None,
                                                      max_cat_to_onehot=None,
                                                      max_delta_step=None,
                                                      max_depth=7,
                                                      max_leaves=None,
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=300,
                                                      n_jobs=None,
                                                      num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'xgb__learning_rate': [0.01, 0.05, 0.1],
                         'xgb__max_depth': [3, 5, 7, 9],
                         'xgb__n_estimator': [200, 300, 500]},
             scoring='roc_auc')

In [97]:
log_grid_pred = log_grid.predict(x_test)
rf_grid_pred = rf_grid.predict(x_test)
xgb_grid_pred = xgb_grid.predict(x_test)

In [98]:
log_grid_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [99]:
rf_grid_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [100]:
xgb_grid_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [ ]:
result_grid = pd.DataFrame({
    'actual' : y_test,
    'log_grid_pred' : log_grid_pred,
    'rf_grid_pred' : rf_grid_pred,
    'xgb_grid_pred' : xgb_grid_pred
})

In [104]:
result_grid.head(20)

actual  log_grid_pred  rf_grid_pred  xgb_grid_pred
179       0              0             0              0
228       0              1             1              1
111       1              1             1              1
246       0              0             0              0
60        1              1             1              1
9         1              1             1              1
119       1              1             1              1
223       0              0             0              0
268       0              0             0              0
33        1              1             1              0
5         1              1             1              1
101       1              0             0              0
45        1              1             1              1
175       0              0             0              0
118       1              1             1              1
46        1              1             1              1
125       1              1             1              1
192       0              0             0              0
285       0              0             0              0
279       0              0             0              0

In [105]:
print(f'roc_auc_score (LogisticRegression-grid) : {roc_auc_score(y_test, log_grid_pred)}')
print(f'roc_auc_score (RandomForestClassifier-grid) : {roc_auc_score(y_test, rf_grid_pred)}')
print(f'roc_auc_score (XGBClassifier-grid) : {roc_auc_score(y_test, xgb_grid_pred)}')

roc_auc_score (LogisticRegression-grid) : 0.8685344827586206
roc_auc_score (RandomForestClassifier-grid) : 0.8669181034482758
roc_auc_score (XGBClassifier-grid) : 0.8200431034482759


In [ ]:
print(f'roc_auc_score (LogisticRegression) : {roc_auc_score(y_test, log_pred)}')
print(f'roc_auc_score (RandomForestClassifier) : {roc_auc_score(y_test, rf_pred)}')
print(f'roc_auc_score (XGBClassifier) : {roc_auc_score(y_test, xgb_pred)}')

roc_auc_score (LogisticRegression) : 0.8529094827586207
roc_auc_score (RandomForestClassifier) : 0.8669181034482758
roc_auc_score (XGBClassifier) : 0.8372844827586207


In [109]:
print(log_grid.best_params_)
print(rf_grid.best_params_)
print(xgb_grid.best_params_)

{'lr__C': 1.0, 'lr__class_weight': None, 'lr__max_iter': 1000}
{'rf__max_depth': 8, 'rf__min_samples_split': 6, 'rf__n_estimators': 300}
{'xgb__learning_rate': 0.01, 'xgb__max_depth': 3, 'xgb__n_estimator': 200}


In [111]:
lr_best = LogisticRegression(
    max_iter = 1000,
    C = 1.0,
    class_weight = None
)

rf_best = RandomForestClassifier(
    n_estimators = 300,
    max_depth = 8,
    min_samples_split = 6
)

xgb_best = XGBClassifier(
    tree_method = 'hist',
    n_estimators = 200,
    max_depth = 3,
    learning_rate = 0.01
)

In [112]:
voting_clf = VotingClassifier(
    estimators=[
        ('lr', lr_best),
        ('rf', rf_best),
        ('xgb', xgb_best)
    ],
    voting='hard',  
    weights=[1, 2, 2]
)

In [113]:
voting_clf.fit(x_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(max_iter=1000)),
                             ('rf',
                              RandomForestClassifier(max_depth=8,
                                                     min_samples_split=6,
                                                     n_estimators=300)),
                             ('xgb',
                              XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, device=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval...
                                            feature_weights=None, gamma=None,
                                            grow_policy=None,
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=0.01, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=3,
                                            max_leaves=None,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=200, n_jobs=None,
                                            num_parallel_tree=None, ...))],
                 weights=[1, 2, 2])

In [114]:
voting_pred = voting_clf.predict(x_test)

In [115]:
vot_result = pd.DataFrame({
    'actual' : y_test,
    'voting_pred' : voting_pred
})

In [117]:
vot_result.head(20)

actual  voting_pred
179       0            0
228       0            1
111       1            1
246       0            0
60        1            1
9         1            1
119       1            1
223       0            0
268       0            0
33        1            1
5         1            1
101       1            0
45        1            1
175       0            0
118       1            1
46        1            1
125       1            1
192       0            0
285       0            0
279       0            0

In [118]:
roc_auc_score(voting_pred, y_test)

0.8709150326797386